### ISSUE TITLE
Single developer Mantil workflow

### ISSUE THREAD

**Issue by ianic** [mantil-io/mantil#20]
# mantil commands

Instalira si Mantil cli na racunalo.

Nema nista drugo. Ne postoji mantil workspace database, njega ce kreirati komande kako bude potrebe.

Kreira novi Mantil project. Moze kreirati prazan projekt (new). Iz nekog template (fork) ili iz svog repozitorija (clone).
Kada kreira iz svog repozitorija racunam da u njega moze kasnije push-ati, to je zapravo isto kao da je napravio git clone.
Kod kreiranja iz template napravi i module rewrite da bi odgovaralo njegovom repozitoriju u koji ce kasnije pushati.
```
mantil new

mantil fork --template=mantil-io/ping  --module-name=github.com/me/my-project

mantil clone mantil-team/my-mantil-project
mantil clone https://github.com/mantil-team/my-mantil-project
mantil clone github.com/mantil-team/my-mantil-project
```
Sve ove komande bi mogle imati i project prefix, ali da je krace pisemo bez project, to je defaultni namespace.
Dugi oblik bi bio:
```
mantil project new
mantil project deploy
mantil project watch
mantil project logs
....
```

Setupira novi account. Kaze nam koje aws credentials da iskoristimo.
```
mantil setup <account-name> --aws-access-key= --aws-secret-key= --aws-region=
mantil setup <account-name> --aws-profile=

mantil setup <account-name> --aws-env
```
Ovo kreira Mantil database u ~/.mantil/. Naziv za workspace je trenutni username.

Ako ne postoji niti jedan account, deploy upozori da najprije mora dodati account.
Prvi deploy napravi dev stage, ako niti jedan stage ne postoji. Ako u tom trenutku postoji vise accounts definirano mora navesti u koji account ide taj stage.
```
mantil deploy
mantil deploy --stage=production
mantil deploy --stage=new-stage-name --account=beta
```

Definira novi stage. Ako ima vise account mora reci u koji account ide taj stage.
```
mantil stage new <stage-name> --account=production
```
Stages postavke se spremaju uz project u /config/project.yml file. Stages mogu imati drugacije postavke environment, secrets, function defaults.
```
workspace: ianic
# defaults for all functions
function:
  - prefix: [default je project name]
  - mem: 128
  - timeout: 1m
stages:
  - dev:
     - default: true
     - account: dev
     - url:
       - https://
       - wss://
     - env:
       - key: value
       - key2: value2
     - secrets:
       - key
       - key2
     - function:
       - name:
         - mem: 512
         - timeout: 15s
```

Prelazak na drugo racunalo. Napravi token i njega importa na drugom racunalu.
```
mantil token new <file-name-for-token> --expires=30d

mantil token import <token-file>
```
Na tom racunalu onda moze napraviti mantil clone (ili samo clone github repozitorija i nastaviti raditi).
Na tom racunalu ne moze dodavati nove account. Stages u postojece accounts moze.

Ako sinkronizira ~/.mantil folder na drugo racunalo onda moze sve. Na njemu je da povuce sinkronizaciju tog foldera (npr. doda ga u iCloud, Dropbox). Tako moze imati full admin prava na vise racunala.

# notes

Sav operativni trosak je njegov.

Podrzavamo:
- vise projekata
- vise racunala
- vise aws accounts

Moze krenuti od template ili od postojeceg projekta.
Moze napraviti projekt prije nego doda account.
Ne kreiramo mu github repozitorij, sve vezano za neki remote repozitorij ostavljemo njemu.
Mantil ima jedan S3 bucket na aws accountu.

# Otvorena pitanja:
Kako updejta cli, kako mantil functions?
Kako prelazi na drugo racunalo? Kako radi s vise racunala?
Sto napraviti kada brise aws accountu iz workspace, a u tom account-u postoje stages?
Kako se odnosimo prema regijama? Svaka regija ima svoj set manti backend funkcija? 
Kako zovem aws account setupiran mantilom?

# setup

- kreira public/private par kljuceva za mantil u tom aws accountu
- zapise te kljuceve u workspace database
- napravi authorizer funkciju na oba api gateway, ta funkcija ima u env postavljen public key
- header u kome dolazi token je "Authorization: [jwt-token]"
- svako izvrsavanje project komandi mora poslati token u headeru
- u tokenu stoji na koji workspace,project,stage se odnosi, koji je user i koja prava ima:
```
workspace: my-workspace
project: my-project
stage: ianic-dev
account: dev
username: ianic
role: owner
```

- token izvadi:
   - ako je workspace owner iz workspace database
   - inace ima token za svaki stage u workspace credentials-ima koje si je importao

Workspace database se nalazi u ~/.mantil/workspace/ianic.yml
Naziv workspace je username tog single developera.
```
name: ianic
access_token_max_age: 2h

accounts:
  - dev:
    keys:
      public: fJK3DwNmNlzOp_XSoVmcYDaFgm5gWaCiii9LN6JX4b0
      private: o1JMHst4lxCV8OnpVb3rD5jEOPcghNRgvWVkNtQhbEF8krcPA2Y2XM6n9dKhWZxgNoWCbmBZoKKKL0s3olfhvQ
    url:
      - wss://myacountapi.execute-api.eu-central-1.amazonaws.com/main
      - http://myacountapi.execute-api.eu-central-1.amazonaws.com/main
  - production:
    keys:
      public: fJK3DwNmNlzOp_XSoVmcYDaFgm5gWaCiii9LN6JX4b0
      private: o1JMHst4lxCV8OnpVb3rD5jEOPcghNRgvWVkNtQhbEF8krcPA2Y2XM6n9dKhWZxgNoWCbmBZoKKKL0s3olfhvQ
    url:
      - wss://u1234nesto.execute-api.eu-central-1.amazonaws.com/main
```
