### ISSUE TITLE
Enable setup of multiple accounts

### ISSUE THREAD

**Issue by djelusic** [mantil-io/mantil#31]
The user should be able to set up multiple AWS accounts to use with mantil. These will be stored in a workspace config located at `~/.mantil/<username>.yml`. Example workspace config:
```
name: daniel
accounts:
- name: dev
  bucket: mantil-eu-central-1-525875336548
  keys:
    public: Bts8CLKoJwP3r_GnMGijsO7BKXsge6EeQq12xP1H_zY
    private: ...
  endpoints:
    rest: https://4dreu7t2t7.execute-api.eu-central-1.amazonaws.com
    ws: wss://xz0pdi1ft1.execute-api.eu-central-1.amazonaws.com
- name: org4
  bucket: mantil-eu-central-1-479496157228
  keys:
    public: YB7z6uqoppvTzq52HSqfQ3jeBBiZDPsgflM1xwHXmjI
    private: ...
  endpoints:
    rest: https://s902mxcpua.execute-api.eu-central-1.amazonaws.com
    ws: wss://mlvru99z35.execute-api.eu-central-1.amazonaws.com
```

The setup command can be used like:
```
mantil aws install <account-name> --aws-access-key=... --aws-secret-key=... --aws-region=...
mantil aws install <account-name> --aws-profile=...
mantil aws install <account-name> --aws-env
```

The default account name is `dev` and it will be used when no account name argument is provided:
```
mantil aws install  --aws-profile=...
```

When setting up a new account a public/private key pair is created for authorization. Every runtime method has a custom lambda authorizer attached which checks the `Authorization` header of incoming requests. This header contains a JWT token created from the private key which encodes all the necessary information for authorization.
