### ISSUE TITLE
Enable project deployment to different stages

### ISSUE THREAD

**Issue by djelusic** [mantil-io/mantil#32]
Users should be able to deploy mantil projects to different stages. Every stage should be independent and have separate underlying infrastructure.

If no stages are deployed yet, `mantil deploy` will create a new one (named `dev` by default, can be changed using the `--stage` flag) and deploy it to a chosen account.
```
mantil deploy
mantil deploy --stage=production
```

Other commands should also have a --stage flag, for example:
```
mantil invoke ping --stage=production
mantil watch --stage=production
mantil destroy --stage=production
```

The project configuration will be saved to `<project_dir>/config/project.yml` and contains the current state of all stages. Example config:
```
name: daniel-test
stages:
- name: dev
  default: true
  account: dev
  endpoints:
    rest: https://hgjn7g2fpl.execute-api.eu-central-1.amazonaws.com
    ws: wss://zcqa6wmq63.execute-api.eu-central-1.amazonaws.com
  functions:
  - name: ping
    hash: edb6647ae6e52b9b59903009373feafd6ed8898edd91e5dedbff0b12dfde4dee
    s3_key: deployments/daniel-test/dev/functions/ping-edb6647ae6e52b9b59903009373feafd6ed8898edd91e5dedbff0b12dfde4dee.zip
    runtime: provided.al2
    handler: bootstrap
    memory_size: 128
    timeout: 900
    path: ping
    env: {}
  public_sites:
  - name: ping
    bucket: static-website-ping-20210930133650747600000001
    hash: h1:GAc8uq3crmmOhWG/GnZQCChsP/5ml6wWDSQQOGE0CBA=
- name: production
  account: dev
  endpoints:
    rest: https://d8j23y80pa.execute-api.eu-central-1.amazonaws.com
    ws: wss://tz5dp03al5.execute-api.eu-central-1.amazonaws.com
  functions:
  - name: ping
    hash: edb6647ae6e52b9b59903009373feafd6ed8898edd91e5dedbff0b12dfde4dee
    s3_key: deployments/daniel-test/production/functions/ping-edb6647ae6e52b9b59903009373feafd6ed8898edd91e5dedbff0b12dfde4dee.zip
    runtime: provided.al2
    handler: bootstrap
    memory_size: 128
    timeout: 900
    path: ping
    env: {}
  public_sites:
  - name: ping
    bucket: static-website-ping-20210930133818088200000001
    hash: h1:GAc8uq3crmmOhWG/GnZQCChsP/5ml6wWDSQQOGE0CBA=
```
